[package]
name = "chain-path-derivation"
version = "0.1.0"
authors = ["Nicolas Di Prima <nicolas@primetype.co.uk>", "Vincent Hanquez <vincent@typed.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = { version = "1.0.13", default-features = false }

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"
paste = "0.1.8"