[package]
name = "jormungandr-lib"
version = "0.1.0"
authors = ["Nicolas Di Prima <nicolas.diprima@iohk.io>", "Vincent Hanquez <vincent.hanquez@iohk.io>"]
edition = "2018"

[dependencies]
bech32 = "0.6"
serde = { version = "1.0", features = ["derive"] }
custom_error = "1.6"
chain-impl-mockchain = { path = "../cardano-deps/chain-impl-mockchain" }
chain-addr      = { path = "../cardano-deps/chain-addr" }
chain-crypto    = { path = "../cardano-deps/chain-crypto" }
rand_core = "0.3"
chrono = { version = "0.4", features = ["serde"] }
humantime = "1.2"

[dev-dependencies]
rand = "0.6"
quickcheck = "0.8"
chain-crypto    = { path = "../cardano-deps/chain-crypto", features = [ "property-test-api" ] }
serde_yaml = "0.8"
bincode = "1.1"
