version: 2

jobs:
  cargo_fetch:
    docker:
      - image: rust:latest
    working_directory: /mnt/crate
    steps:
      - checkout
      - run:
          name: Get top commit hash of cargo registry index
          command: |
            git ls-remote --heads https://github.com/rust-lang/crates.io-index.git master |
              cut -f 1 | tee .circleci/crates.io-index.head
      - restore_cache:
          name: Restore cargo registry index from cache
          keys:
            - cargo-index-v1-{{ checksum ".circleci/crates.io-index.head" }}
            - cargo-index-v1-
      - run:
          name: Generate Cargo.lock
          command: |
            cargo generate-lockfile
            git -C /usr/local/cargo/registry/index/github.com-1ecc6299db9ec823 \
                show-ref -s refs/remotes/origin/master |
              tee .circleci/crates.io-index.head
      - save_cache:
          name: Save cargo registry index into cache
          key: cargo-index-v1-{{ checksum ".circleci/crates.io-index.head" }}
          paths:
            - /usr/local/cargo/registry/index
      - restore_cache:
          name: Restore dependency crates from cache
          keys:
            - cargo-deps-v1-{{ checksum "Cargo.lock" }}
            - cargo-deps-v1-
      - run: cargo fetch
      - save_cache:
          name: Save dependency crates into cache
          key: cargo-deps-v1-{{ checksum "Cargo.lock" }}
          paths:
            - /usr/local/cargo/registry/cache
      - persist_to_workspace:
          root: /mnt/crate
          paths:
            - Cargo.lock
            - .circleci/crates.io-index.head

  #rustfmt:
  #  docker:
  #    - image: rust:latest
  #  working_directory: /mnt/crate
  #  steps:
  #    - checkout
  #    - run:
  #        name: Install rustfmt
  #        command: rustup component add rustfmt
  #    - run:
  #        name: Print version information
  #        command: cargo fmt -- --version
  #    - run:
  #        name: Check rustfmt
  #        command: cargo fmt -- --check

  test_debug:
    docker:
      - image: rust:latest
    working_directory: /mnt/crate
    steps:
      - checkout
      - attach_workspace:
          at: /mnt/crate
      - restore_cache:
          name: Restore cargo registry index from cache
          keys:
            - cargo-index-v1-{{ checksum ".circleci/crates.io-index.head" }}
      - restore_cache:
          name: Restore dependency crates from cache
          keys:
            - cargo-deps-v1-{{ checksum "Cargo.lock" }}
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: Build
          command: cargo build --tests --verbose --frozen
      - run:
          name: Test
          environment:
            RUST_BACKTRACE: 1
          command: cargo test --verbose --frozen

  test_release:
    docker:
      - image: rust:latest
    working_directory: /mnt/crate
    steps:
      - checkout
      - attach_workspace:
          at: /mnt/crate
      - restore_cache:
          name: Restore cargo registry index from cache
          keys:
            - cargo-index-v1-{{ checksum ".circleci/crates.io-index.head" }}
      - restore_cache:
          name: Restore dependency crates from cache
          keys:
            - cargo-deps-v1-{{ checksum "Cargo.lock" }}
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: Build
          command: cargo build --tests --verbose --frozen --release
      - run:
          name: Test
          command: cargo test --verbose --frozen --release

  test_nightly:
    docker:
      - image: rustlang/rust:nightly
    working_directory: /mnt/crate
    steps:
      - checkout
      - attach_workspace:
          at: /mnt/crate
      - restore_cache:
          name: Restore cargo registry index from cache
          keys:
            - cargo-index-v1-{{ checksum ".circleci/crates.io-index.head" }}
      - restore_cache:
          name: Restore dependency crates from cache
          keys:
            - cargo-deps-v1-{{ checksum "Cargo.lock" }}
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: Build
          command: cargo build --tests --verbose --frozen
      - run:
          name: Test
          environment:
            RUST_BACKTRACE: 1
          command: cargo test --verbose --frozen

workflows:
  version: 2
  test_all:
    jobs:
      - cargo_fetch
      #- rustfmt
      - test_debug:
          requires:
            #- rustfmt
            - cargo_fetch
      - test_release:
          requires:
            #- rustfmt
            - cargo_fetch
      - test_nightly:
          requires:
            #- rustfmt
            - cargo_fetch
