[package]
name = "hdwallet"
version = "0.1.0"
authors = ["Vincent Hanquez <vincent@typed.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
cryptoxide = "0.2.0"
ed25519-bip32 = "^0.3.1"
bip39 = { path = "../bip39" }
cbor_event = "^2.1.3"
thiserror = { version = "1.0.13", default-features = false }
chain-path-derivation = { path = "../chain-path-derivation" }
