[package]
name = "hdwallet"
version = "0.1.0"
authors = ["Vincent Hanquez <vincent@typed.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ed25519-bip32 = "^0.1.4"
bip39 = { path = "../bip39" }
bip44 = { path = "../bip44" }
cryptoxide = "0.1.2"
cbor_event = "2.1"
