[workspace]
members = [
    "rcw",
    "cardano",
    "blockchain",
    "wallet-cli",
    "protocol",
    "storage",
    "hermes",
    "cbor",
]
[dependencies]
printer = { path = "rust-crypto-wasm" }
