[package]
name = "blockchain"
version = "0.1.0"
authors = ["Nicolas Di Prima <nicolas.diprima@iohk.io>"]
edition = "2018"

[dependencies]
chain-impl-mockchain = { git = "https://github.com/Mr-Leshiy/chain-libs.git", branch = "tally-share-validation" }
chain-time           = { git = "https://github.com/Mr-Leshiy/chain-libs.git", branch = "tally-share-validation"}
thiserror = "1.0.26"
lru       = "0.6.6"
