[package]
name = "chain-impl-mockchain"
version = "0.1.0"
authors = [ "Nicolas Di Prima <nicolas.diprima@iohk.io>"
          , "Vincent Hanquez <vincent.hanquez@iohk.io>"
          , "Eelco Dolstra <edolstra@gmail.com>"
          , "Mikhail Zabaluev <mikhail.zabaluev@gmail.com>"
          , "Alexander Vershilov <alexander.vershilov@gmail.com>"
          ]
edition = "2018"

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
bincode = "^1.0.1"
quickcheck = { version = "0.8" }
chain-core = { path = "../chain-core" }
chain-addr = { path = "../chain-addr" }
rand = "0.6"

[dependencies.cardano]
path = "../cardano"
features = [ "generic-serialization" ]

[dev-dependencies]
chain-core = { path = "../chain-core", features=["property-test-api"]}
chain-addr = { path = "../chain-addr", features=["property-test-api"]}
