[package]
name = "bip39"
version = "0.1.0"
authors = ["Vincent Hanquez <vincent@typed.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cryptoxide = "0.1"

[dev-dependencies]
unicode-normalization = "*"
rand = "*"
hex = "*"