[package]
name = "imhamt"
version = "0.1.0"
authors = ["Vincent Hanquez <vincent.hanquez@iohk.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"

[target.'cfg(unix)'.dev-dependencies]
jemalloc-ctl = "*"
jemallocator = "*"

[features]
default = []
with-bench = []
optimized-node = []

[[example]]
name = "memdump"
path = "examples/memdump/main.rs"
