name: Coveralls Test Code Coverage

on:
  push:
    branches: [ "main", "feature/add-ci-coveralls" ]
    paths-ignore: ["README.md", "CODE_OF_CONDUCT.md", "CONTRIBUTING.md"]
  pull_request:
    paths-ignore: ["README.md", "CODE_OF_CONDUCT.md", "CONTRIBUTING.md"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0

jobs:
  vit_servicing_station:
    name: Vit Servicing Station Tests
    runs-on: ubuntu-latest
    env:
      CARGO_FLAGS: --verbose --locked
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: Swatinem/rust-cache@v2

      - name: Install Nextest
        run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - name: Install deps
        run:
          sudo apt install -y protobuf-compiler libssl-dev libpq-dev libsqlite3-dev pkg-config

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Run vit-ss test coverage
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.65"  # it says it can read the rust-toolchain file, but it fails if we omit this
      - run: |
          cargo build -p vit-servicing-station-cli -p vit-servicing-station-server
          cargo llvm-cov nextest --no-report --manifest-path ./src/vit-servicing-station/vit-servicing-station-cli/Cargo.toml --profile ci
          cargo llvm-cov nextest --no-report --manifest-path ./src/vit-servicing-station/ vit-servicing-station-lib/Cargo.toml --profile ci
          cargo llvm-cov nextest --no-report --manifest-path ./src/vit-servicing-station/ vit-servicing-station-tests/Cargo.toml --profile ci
          cargo llvm-cov nextest --no-report --manifest-path ./src/vit-servicing-station/ vit-servicing-station-server/Cargo.toml --profile ci
          cargo llvm-cov report --lcov

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./lcov.info"
