name: Coveralls Test Code Coverage

on:
  push:
    branches: [ "feature/add-ci-coveralls" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0

concurrency:
  group: ${{ github.sha }}
  cancel-in-progress: true

jobs:
  monorepo:
    name: Catalyst Core Coverage
    runs-on: ubuntu-latest
    env:
      CARGO_FLAGS: --verbose --locked
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-nextest
        run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Install system deps
        run:
          sudo apt install -y protobuf-compiler libssl-dev libpq-dev libsqlite3-dev pkg-config

      - name: Run vit-ss tests and coverage info
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.65"  # it says it can read the rust-toolchain file, but it fails if we omit this
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/catalyst-toolbox/catalyst-toolbox/Cargo.toml --profile ci
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/catalyst-toolbox/snapshot-lib/Cargo.toml --profile ci
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/vit-servicing-station/vit-servicing-station-cli/Cargo.toml --profile ci
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/vit-servicing-station/vit-servicing-station-lib/Cargo.toml --profile ci
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/vit-servicing-station/vit-servicing-station-server/Cargo.toml --profile ci
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/voting-tools-rs/Cargo.toml --profile ci
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/chain-libs/cardano-legacy-address/Cargo.toml
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/chain-libs/chain-addr/Cargo.toml
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/chain-libs/chain-core/Cargo.toml
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/chain-libs/chain-crypto/Cargo.toml
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/chain-libs/chain-evm/Cargo.toml
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/chain-libs/chain-impl-mockchain/Cargo.toml
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/chain-libs/chain-network/Cargo.toml
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/chain-libs/chain-ser/Cargo.toml
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/chain-libs/chain-storage/Cargo.toml
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/chain-libs/chain-time/Cargo.toml
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/chain-libs/chain-vote/Cargo.toml
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/chain-libs/imhamt/Cargo.toml
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/chain-libs/sparse-array/Cargo.toml
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/chain-libs/typed-bytes/Cargo.toml
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/chain-wallet-libs/bindings/wallet-c/Cargo.toml
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/chain-wallet-libs/bindings/wallet-core/Cargo.toml
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/chain-wallet-libs/bindings/wallet-wasm-js/Cargo.toml
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/chain-wallet-libs/chain-path-derivation/Cargo.toml
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/chain-wallet-libs/hdkeygen/Cargo.toml
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/chain-wallet-libs/symmetric-cipher/Cargo.toml
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/chain-wallet-libs/wallet/Cargo.toml
      - run:
          cargo llvm-cov nextest --no-report --manifest-path ./src/jormungandr/jormungandr/Cargo.toml
      - run:
          cargo llvm-cov report --lcov --output-path ./lcov.info

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./lcov.info"
