name: GitHub Pages

on:
  push:
    branches: 
      - "main"
      - "docs-ci"
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Update local toolchain
        run: |
          rustup update
          cargo install cargo-make
          
      - name: Setup mdBook prerequisites 
        run: |
          cargo make install-docs-prereqs

      - name: Build the book
        run: |
          mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/docs-ci' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/html