name: Javascript wallet binding

on:
  push:
    branches: [ "feature/npg-3884-setup-js-ci" ]
  pull_request:
    branches: [ "main" ]

jobs:
  wallet-js-binding:
    permissions: 
      contents: read
      packages: write 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        # Optional version of wasm-pack to install(eg. 'v0.9.1', 'latest')
        version: 'latest'
    
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        registry-url: 'https://npm.pkg.github.com'
        # Defaults to the user or organization that owns the workflow fileлс
        scope: '@Mr-Leshiy'
    
    - name: Build wasm package
      run: |
        cd src/chain-wallet-libs/bindings/wallet-js
        wasm-pack build --target=nodejs -d pkg

    - name: JS tests
      run: |
        cd src/chain-wallet-libs/bindings/wallet-js/js-test
        npm install
        npm test
    - name: Publish
      run: |
        cd src/chain-wallet-libs/bindings/wallet-js/pkg
        npm install
        npm ci
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    