name: CI-Tests

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      RUSTFLAGS: -D warnings
      RUST_BACKTRACE: 1
      CARGO_FLAGS: --verbose --locked
      CARGO_INCREMENTAL: 0
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run tests
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - run: nix-shell --run ".github/jormungandr_tests.sh 1 1"

