name: CI-Tests

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardNumber: [1, 2, 3, 4, 5, 6, 7, 8]
        totalShards: [8]
    env:
      RUSTFLAGS: -D warnings
      RUST_BACKTRACE: 1
      CARGO_FLAGS: --verbose --locked
      CARGO_INCREMENTAL: 0
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: Swatinem/rust-cache@v2
      - name: Free disk space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          df -h
      - name: Install Nextest
        run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
      - name: Install deps
        run:
          sudo apt install -y protobuf-compiler libssl-dev libpq-dev

      - name: Run tests
        uses: actions-rs/toolchain@v1
      - run: |
          cargo build -p jormungandr
          cargo build -p jcli
          cargo nextest run --no-fail-fast --partition hash:${{ shardNumber }}/${{ totalShards }}


